export const data = [
  {
    id: "1",
    productTitle: "Colors",
    icon: "icons/drop.svg",
    smenu1: "Add Color",
    smenu1Link:'/view-addcolor',
    smenu2: "View Color",
    smenu2Link:'/view-color',
  },
  {
    id: "2",
    productTitle: "Size",
    icon: "icons/size.svg",
    smenu1: "Size Details",
    smenu1Link:'/size-details',
    smenu2: "View Size",
    smenu2Link:'/size-view',
  },
  {
    id: "3",
    productTitle: "Parent Category",
    icon: "icons/ParentCategory.svg",
    smenu1: "Add Category",
    smenu1Link:'/add-category',
    smenu2: "View Category",
    smenu2Link:'/view-category',
  },
  {
    id: "4",
    productTitle: "Sub Category",
    icon: "icons/subcat.svg",
    smenu1: "Add Sub Category",
    smenu1Link:'/add-subcategory',
    smenu2: "View Sub Category",
    smenu2Link:'/view-subcategory',
   
   
  },
  {
    id: "5",
    productTitle: "Product",
    icon: "icons/product.svg",
    smenu1: "Product Details",
    smenu1Link:'/product-details',
    smenu2: "Product Items",
    smenu2Link:'/product-items',
  },
  {
    id: "6",
    productTitle: "Story",
    icon: "icons/story.svg",
    smenu1: "Story Details",
    smenu1Link:'/story-details',
    smenu2: "Story View",
    smenu2Link:'/story-view',
  },
  {
    id: "7",
    productTitle: "Order",
    icon: "icons/order.svg",
    smenu1: "Order",
    smenu1Link:'/order-view',
  },
  {
    id: "8",
    productTitle: "Slider",
    icon: "icons/sidebar.svg",
    smenu1: "Slider Details",
    smenu1Link:'/slider-details',
    smenu2: "Slider View",
    smenu2Link:'/slider-view',
  },
  {
    id: "9",
    productTitle: "Terms & Conditions",
    icon: "icons/terms.svg",
   
   
  },
];
